[package]
name = "concurrent-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
